spring:
  application:
    name: apigateway

server:
  port: 8080

zuul:
  ignored-headers:
  sensitiveHeaders:
  ignoredServices: '*'
  routes:
    user:
      path: /user/**
      service-id: user
    catalog:
      path: /catalog/**
      service-id: catalog
    order:
      path: /order/**
      service-id: order

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    routes:
      enabled: true
    web:
      exposures:
        include: "*"